### ISSUE TITLE
English version available?

### ISSUE THREAD

**Issue by mikejdolan** [openfun/password-container-xblock#2]
Does anyone know if there is a version of this x-block available for English speaking students?

**Comment by rmoch** [comment]
Not for now, but we plan to improve this work in the next months.

**Comment by mikejdolan** [comment]
Thanks. Please let us know if we can help.

**Comment by rmoch** [comment]
ping @mikejdolan, we just merged english internationalisation done by @oksana-slu 
Enjoy

**Comment by mikejdolan** [comment]
Thanks Richard!

On Tue, Jan 12, 2016 at 11:02 AM, Richard Moch notifications@github.com
wrote:

> ping @mikejdolan https://github.com/mikejdolan, we just merged english
> internationalisation done by @oksana-slu https://github.com/oksana-slu
> Enjoy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openfun/password-container-xblock/issues/2#issuecomment-170975975
> .

## 

---

Michael Dolan
Managing Director
Socratic Brain
mdolan@socraticbrain.org
512-477-2839
Linked in profile: http://www.linkedin.com/in/michaeldolan16
